import numpy as np 
from matplotlib import pyplot as plt

def plot_stm_from_dat(file: str, gridsize: int = 300):
    '''Plots a STM from a .dat file generated by Critic2'''
    data = np.loadtxt(file)
    plt.hexbin(data[:,2], data[:,3], C=data[:,4], gridsize=gridsize, cmap='Greys_r')
    plt.colorbar(label='Relative Height (arb. units)')
    plt.show()
