package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

type Atom struct {
	AtomType string
	X        float64
	Y        float64
	Z        float64
}

func main() {
	if len(os.Args) != 2 {
		fmt.Println("Usage: xyz2psocar <xyz_file>")
		os.Exit(1)
	}

	// Read in the atoms from the input file
	var atoms []Atom
	file, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Printf("Error opening file: %s\n", err)
		os.Exit(1)
	}
	defer file.Close()
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) != 4 {
			continue
		}

		atomType := fields[0]
		x, err := strconv.ParseFloat(fields[1], 64)
		if err != nil {
			fmt.Printf("Error parsing x coordinate: %s\n", err)
			os.Exit(1)
		}
		y, err := strconv.ParseFloat(fields[2], 64)
		if err != nil {
			fmt.Printf("Error parsing y coordinate: %s\n", err)
			os.Exit(1)
		}
		z, err := strconv.ParseFloat(fields[3], 64)
		if err != nil {
			fmt.Printf("Error parsing z coordinate: %s\n", err)
			os.Exit(1)
		}
		atoms = append(atoms, Atom{
			AtomType: atomType,
			X:        x,
			Y:        y,
			Z:        z,
		})
	}

	// Sort the atoms by atom type
	sort.Slice(atoms, func(i, j int) bool {
		return atoms[i].AtomType < atoms[j].AtomType
	})

	// Get atom types and counts
	var atomTypes []string
	var atomCounts []int
	for _, atom := range atoms {
		if len(atomTypes) == 0 || atomTypes[len(atomTypes)-1] != atom.AtomType {
			atomTypes = append(atomTypes, atom.AtomType)
			atomCounts = append(atomCounts, 1)
		} else {
			atomCounts[len(atomCounts)-1]++
		}
	}

	// Print the atoms in PSOCAR format
	fmt.Println("PSOCAR generated by vsh")
	fmt.Println("1")

	// Print lattice vectors 15x15x15
	fmt.Println("15.000000000000000 0.0000000000000000 0.0000000000000000")
	fmt.Println("0.0000000000000000 15.000000000000000 0.0000000000000000")
	fmt.Println("0.0000000000000000 0.0000000000000000 15.000000000000000")

	// Print atom types separated by spaces
	for _, atomType := range atomTypes {
		fmt.Printf("%s ", atomType)
	}

	// Print atom counts separated by spaces
	fmt.Println()
	for _, atomCount := range atomCounts {
		fmt.Printf("%d ", atomCount)
	}

	fmt.Println()

	for _, atom := range atoms {
		fmt.Printf("%f %f %f %s\n", atom.X, atom.Y, atom.Z, atom.AtomType)
	}
}

